title: The Nuances of React Transition Group
description: What exactly react-transition-group does and how to use it correctly to create delightful transitions.
category: DEV
published: 2018-03-16
tweet: https://twitter.com/silvenon/status/974740929025323009
