title: Managing complex tasks with gulp v4
description: Replace large npm scripts with gulp tasks elegantly composed using new gulp API.
category: DEV
published: 2020-07-20
tweet: https://twitter.com/silvenon/status/1285326527660470272
lastModified: 2020-07-22
