root: true
parser: babel-eslint
extends:
  - airbnb
rules:
  semi:
    - error
    - never
  no-shadow: off
  no-confusing-arrow: off
  import/prefer-default-export: off
  react/prop-types: off
  react/jsx-filename-extension: off
  react/jsx-wrap-multilines: off