root: true
parser: babel-eslint
plugins:
  - prettier
  - flowtype
extends:
  - airbnb
  - plugin:flowtype/recommended
  - prettier
  - prettier/flowtype
  - prettier/react
rules:
  no-shadow: off
  import/prefer-default-export: off
  react/default-props-match-prop-types:
    - error
    - allowRequiredDefaults: true
  react/destructuring-assignment: off
  react/jsx-filename-extension: off
  react/no-unescaped-entities: off
  react/prop-types: off
  react/require-default-props:
    - error
    - forbidDefaultForRequired: false
  react/sort-comp: off
  prettier/prettier: error

overrides:
  - files:
      - "**/*.test.js"
      - "__tests__/**/*.js"
    env:
      jest: true
