root: true
parser: babel-eslint
plugins:
  - prettier
  - flowtype
extends:
  - airbnb
  - plugin:flowtype/recommended
  - prettier
  - prettier/flowtype
  - prettier/react
rules:
  no-shadow: off
  import/prefer-default-export: off
  react/destructuring-assignment: off
  react/jsx-filename-extension: off
  react/no-unescaped-entities: off
  react/prop-types: off
  prettier/prettier: error
