seriesPart: 1
title: Staging Accurately
description: In order to record meaningful sets of changes, we need to learn how to select exactly what we want through partial staging and unstaging.
category: DEV
