title: Downvoting Comments on YouTube Does Nothing
description: While watching a video about the terrifying comments that women on YouTube have to endure daily, the downvoting feature caught my attention.
category: NON_DEV
published: 2016-09-01
