title: On Code Folding and Minimaps
description: What frequent use of code folding and the minimap feature might indicate about our codebase.
category: DEV
published: 2018-04-03
tweet: https://twitter.com/silvenon/status/981242225731436544
