title: Make your JavaScript project accessible to newcomers
description: Introduction to the concept of developer experience and advice on why and how to improve it in JavaScript projects.
category: DEV
published: 2021-04-06
