seriesPart: 3
title: Resolving Conflicts
description: Git conflicts are a dreaded topic, but the discomfort usually stems from the fact that they are unexpected. So let's talk about them here, very expectedly.
category: DEV
