title: Checking your static site for dead URLs
description: One of the challenges of maintaining a static site is continuously ensuring that links work, both local and external.
category: DEV
published: 2020-07-26
tweet: https://twitter.com/silvenon/status/1287337375681699840
