title: Why I Migrated Away from Medium
description: Missing features and odd aspects of Medium that eventually drove me away.
category: DEV
published: 2018-09-13
tweet: https://twitter.com/silvenon/status/1040220215798374400
