title: A Built-in Alternative to Redux with React Context and Hooks
description: A summary of multiple posts by Kent C. Dodds about how to imitate Redux using modern React API.
category: DEV
published: 2019-08-02
lastModified: 2019-08-04
tweet: https://twitter.com/silvenon/status/1157204419047493633
