title: Intro to ESLint (ft. Daft Punk)
description: How ESLint can improve the quality of your project and even teach you JavaScript.
category: DEV
published: 2016-06-01
tweet: https://twitter.com/silvenon/status/737979934648508416
