title: Custom Project-Based ESLint Rules
description: How to create custom ESLint rules using an existing rule and AST selectors.
category: DEV
published: 2017-12-02
tweet: https://twitter.com/silvenon/status/937069708817387520
